[project]
name = "llm-adsorbate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ase>=3.26.0",
    "autoadsorbate>=0.2.2",
    "llm-openrouter>=0.4.1",
    "pandas>=2.3.2",
    "weave>=0.52.6",
]
